version: '3'

services:

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlrootpassword
      - MYSQL_DATABASE=example_db
      - MYSQL_USER=example_user
      - MYSQL_PASSWORD=examplepassword

  app:
    build:
      context: .
      dockerfile: Dockerfile      
    image: nodejs-app:latest
    env_file: .env
    environment:
      - SERVER_TEXT=$SERVER_TEXT
      - SERVER_PORT=$SERVER_PORT
      - DB_ADDRESS=db
      - DB_PORT=$DB_PORT
      - DB_NAME=$DB_NAME
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
#    volumes:
#      - './:/home/node/app'
#    working_dir: '/home/node/app'
    ports:
      - '3000:3000'
    depends_on:
      - db

